# Generated by Django 4.2.4 on 2023-09-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('employee_phone', models.CharField(max_length=10)),
                ('employee_address', models.CharField(max_length=100)),
                ('is_working', models.BooleanField(default=True)),
                ('department', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
